[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.24"
evm_version = "cancun"
fuzz_runs = 5000
fuzz_max_global_rejects = 2_000_000
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
arbitrum = "${ARBITRUM_RPC_URL}"
scroll_testnet = "${SCROLL_TESTNET_RPC_URL}"


# See more config options https://github.com/foundry-rs/foundry/tree/master/config